language: csharp
solution: SeeSharpLiveStreaming.sln
install:
  - export MONO_INTEGRATION_MODE=True
  - nuget restore SeeSharpLiveStreaming.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SeeSharpLiveStreaming.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SeeSharpLiveStreaming.Tests/bin/Release/SeeSharpHttpLiveStreaming.Tests.dll
